/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Billing;
/**
 *
 * @author miltos
 */
public class BillingSystem extends javax.swing.JFrame {

    String operations;
    String answer;
    double firstnum,secondnum,result;
    /**
     * Creates new form BillingSystem
     */
    public BillingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        jButton_div = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton_dot = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton_plus = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton_mod = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton_sub = new javax.swing.JButton();
        jButton_percent = new javax.swing.JButton();
        jButton_ans = new javax.swing.JButton();
        jButton_CE = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox_Pizza = new javax.swing.JCheckBox();
        jCheckBox_Fruits = new javax.swing.JCheckBox();
        jCheckBox_Wafers = new javax.swing.JCheckBox();
        jCheckBox_Biscuits = new javax.swing.JCheckBox();
        jCheckBox_Veges = new javax.swing.JCheckBox();
        jTextField_Veges = new javax.swing.JTextField();
        jTextField_Pizza = new javax.swing.JTextField();
        jTextField_Wafers = new javax.swing.JTextField();
        jTextField_Biscuits = new javax.swing.JTextField();
        jTextField_Fruits = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField_TCI = new javax.swing.JTextField();
        jTextField_TDC = new javax.swing.JTextField();
        jTextField_TCM = new javax.swing.JTextField();
        jTextField_CGST = new javax.swing.JTextField();
        jTextField_SGST = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_SGST = new javax.swing.JLabel();
        jLabel_TCI = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_ST = new javax.swing.JLabel();
        jLabel_tax = new javax.swing.JLabel();
        jLabel_ta = new javax.swing.JLabel();
        jTextField_ST = new javax.swing.JTextField();
        jTextField_TAX = new javax.swing.JTextField();
        jTextField_TA = new javax.swing.JTextField();
        jButton_clc = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setSize(new java.awt.Dimension(1300, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 360));

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayActionPerformed(evt);
            }
        });

        jButton_div.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton_div.setText("/");
        jButton_div.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_divActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton7.setText("7");
        jButton7.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton5.setText("5");
        jButton5.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton1.setText("1");
        jButton1.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton2.setText("2");
        jButton2.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton0.setText("0");
        jButton0.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton_dot.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton_dot.setText(".");
        jButton_dot.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dotActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton9.setText("9");
        jButton9.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton_plus.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton_plus.setText("+");
        jButton_plus.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_plusActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton6.setText("6");
        jButton6.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton8.setText("8");
        jButton8.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton3.setText("3");
        jButton3.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton_mod.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton_mod.setText("*");
        jButton_mod.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton4.setText("4");
        jButton4.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton_sub.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton_sub.setText("-");
        jButton_sub.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_subActionPerformed(evt);
            }
        });

        jButton_percent.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton_percent.setText("%");
        jButton_percent.setPreferredSize(new java.awt.Dimension(60, 50));
        jButton_percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_percentActionPerformed(evt);
            }
        });

        jButton_ans.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton_ans.setText("=");
        jButton_ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ansActionPerformed(evt);
            }
        });

        jButton_CE.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton_CE.setText("CE");
        jButton_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_plus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_percent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_plus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_percent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 330, 390));
        jPanel1.getAccessibleContext().setAccessibleName("");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jCheckBox_Pizza.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox_Pizza.setText("Pizza");
        jCheckBox_Pizza.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox_Pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_PizzaActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox_Pizza);
        jCheckBox_Pizza.setBounds(10, 120, 140, 49);

        jCheckBox_Fruits.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox_Fruits.setText("Fruits");
        jCheckBox_Fruits.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox_Fruits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_FruitsActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox_Fruits);
        jCheckBox_Fruits.setBounds(10, 20, 140, 49);

        jCheckBox_Wafers.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox_Wafers.setText("Wafers");
        jCheckBox_Wafers.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox_Wafers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_WafersActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox_Wafers);
        jCheckBox_Wafers.setBounds(10, 170, 140, 49);

        jCheckBox_Biscuits.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox_Biscuits.setText("Biscuits");
        jCheckBox_Biscuits.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox_Biscuits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_BiscuitsActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox_Biscuits);
        jCheckBox_Biscuits.setBounds(10, 220, 140, 49);

        jCheckBox_Veges.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jCheckBox_Veges.setText("Veges");
        jCheckBox_Veges.setPreferredSize(new java.awt.Dimension(130, 49));
        jCheckBox_Veges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_VegesActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox_Veges);
        jCheckBox_Veges.setBounds(10, 70, 140, 49);

        jTextField_Veges.setEditable(false);
        jTextField_Veges.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_Veges.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Veges.setText("0");
        jPanel2.add(jTextField_Veges);
        jTextField_Veges.setBounds(150, 70, 90, 40);

        jTextField_Pizza.setEditable(false);
        jTextField_Pizza.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_Pizza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Pizza.setText("0");
        jPanel2.add(jTextField_Pizza);
        jTextField_Pizza.setBounds(150, 120, 90, 40);

        jTextField_Wafers.setEditable(false);
        jTextField_Wafers.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_Wafers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Wafers.setText("0");
        jPanel2.add(jTextField_Wafers);
        jTextField_Wafers.setBounds(150, 170, 90, 40);

        jTextField_Biscuits.setEditable(false);
        jTextField_Biscuits.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_Biscuits.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Biscuits.setText("0");
        jPanel2.add(jTextField_Biscuits);
        jTextField_Biscuits.setBounds(150, 220, 90, 40);

        jTextField_Fruits.setEditable(false);
        jTextField_Fruits.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_Fruits.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Fruits.setText("0");
        jPanel2.add(jTextField_Fruits);
        jTextField_Fruits.setBounds(150, 20, 90, 40);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jTextField_TCI.setEditable(false);
        jTextField_TCI.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_TCI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_TCI.setText("0");
        jPanel3.add(jTextField_TCI);
        jTextField_TCI.setBounds(350, 30, 160, 40);

        jTextField_TDC.setEditable(false);
        jTextField_TDC.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_TDC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_TDC.setText("0");
        jPanel3.add(jTextField_TDC);
        jTextField_TDC.setBounds(350, 90, 160, 40);

        jTextField_TCM.setEditable(false);
        jTextField_TCM.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_TCM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_TCM.setText("0");
        jPanel3.add(jTextField_TCM);
        jTextField_TCM.setBounds(350, 150, 160, 40);

        jTextField_CGST.setEditable(false);
        jTextField_CGST.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_CGST.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_CGST.setText("0");
        jPanel3.add(jTextField_CGST);
        jTextField_CGST.setBounds(350, 210, 160, 40);

        jTextField_SGST.setEditable(false);
        jTextField_SGST.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField_SGST.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_SGST.setText("0");
        jPanel3.add(jTextField_SGST);
        jTextField_SGST.setBounds(350, 270, 160, 40);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Total Cost of Mileage");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 150, 320, 40);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setText("CGST");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 210, 320, 40);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setText("Total Delivery Cost");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 90, 320, 40);

        jLabel_SGST.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel_SGST.setText("SGST");
        jPanel3.add(jLabel_SGST);
        jLabel_SGST.setBounds(20, 270, 320, 40);

        jLabel_TCI.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel_TCI.setText("Total Cost of Items");
        jPanel3.add(jLabel_TCI);
        jLabel_TCI.setBounds(20, 30, 320, 40);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(250, 10, 550, 370);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 820, 390));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_ST.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_ST.setText("Sub Total");

        jLabel_tax.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_tax.setText("Tax");

        jLabel_ta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel_ta.setText("Total Amount");

        jTextField_ST.setEditable(false);
        jTextField_ST.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField_ST.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_ST.setText("Rs. 0.0");

        jTextField_TAX.setEditable(false);
        jTextField_TAX.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField_TAX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_TAX.setText("Rs. 0.0");

        jTextField_TA.setEditable(false);
        jTextField_TA.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField_TA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_TA.setText("Rs. 0.0");

        jButton_clc.setText("Calculate");
        jButton_clc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clcActionPerformed(evt);
            }
        });

        jButton_clear.setText("Clear");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_ta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(194, 194, 194)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_ST, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jTextField_TAX)
                    .addComponent(jTextField_TA))
                .addGap(86, 86, 86)
                .addComponent(jButton_clc, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(656, Short.MAX_VALUE)
                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(321, 321, 321)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ST)
                    .addComponent(jTextField_ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_tax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_ta)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField_TAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_TA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_clc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 401, 1150, 130));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayActionPerformed

    private void jButton_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_divActionPerformed
        firstnum= Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations="/";
    }//GEN-LAST:event_jButton_divActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String EnterNumber=txtDisplay.getText()+jButton7.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String EnterNumber=txtDisplay.getText()+jButton5.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String EnterNumber=txtDisplay.getText()+jButton1.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String EnterNumber=txtDisplay.getText()+jButton2.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        String EnterNumber=txtDisplay.getText()+jButton0.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dotActionPerformed
     if(!txtDisplay.getText().contains(".")){
     txtDisplay.setText(txtDisplay.getText()+jButton_dot.getText());
     }
    }//GEN-LAST:event_jButton_dotActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String EnterNumber=txtDisplay.getText()+jButton9.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_plusActionPerformed
        firstnum= Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations="+";
    }//GEN-LAST:event_jButton_plusActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      String EnterNumber=txtDisplay.getText()+jButton6.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String EnterNumber=txtDisplay.getText()+jButton8.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String EnterNumber=txtDisplay.getText()+jButton3.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modActionPerformed
        firstnum= Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations="*";
    }//GEN-LAST:event_jButton_modActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String EnterNumber=txtDisplay.getText()+jButton4.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_subActionPerformed
        firstnum= Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations="-";
    }//GEN-LAST:event_jButton_subActionPerformed

    private void jButton_percentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_percentActionPerformed
        firstnum= Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations="%";
    }//GEN-LAST:event_jButton_percentActionPerformed

    private void jButton_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CEActionPerformed
        txtDisplay.setText("");
    }//GEN-LAST:event_jButton_CEActionPerformed

    private void jButton_ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ansActionPerformed
        secondnum = Double.parseDouble(txtDisplay.getText());
        if(operations == "+"){
        result=firstnum+secondnum;
        answer=String.format("%2f",result);
        txtDisplay.setText(answer);
        }
        else if(operations =="-"){
        result=firstnum-secondnum;
        answer=String.format("%2f",result);
        txtDisplay.setText(answer);
        }
        else if(operations =="*"){
        result=firstnum*secondnum;
        answer=String.format("%2f",result);
        txtDisplay.setText(answer);
        }
        else if(operations =="/"){
        result=firstnum/secondnum;
        answer=String.format("%2f",result);
        txtDisplay.setText(answer);
        }
        else {
        result=firstnum%secondnum;
        answer=String.format("%2f",result);
        txtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jButton_ansActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
//        String EnterNumber=txtDisplay.getText()+jButton7.getText();
//        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jCheckBox_PizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_PizzaActionPerformed
        if(jCheckBox_Pizza.isSelected()){
        jTextField_Pizza.setEditable(true);
        jTextField_Pizza.setText("");
        jTextField_Pizza.requestFocus();
        }
        else{
        jTextField_Pizza.setEditable(false);
        jTextField_Pizza.setText("0");
        }
    }//GEN-LAST:event_jCheckBox_PizzaActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        txtDisplay.setText("");
        jTextField_Fruits.setText("0");
        jTextField_Veges.setText("0");
        jTextField_Pizza.setText("0");
        jTextField_Wafers.setText("0");
        jTextField_Biscuits.setText("0");
        jTextField_TCI.setText("0");
        jTextField_TDC.setText("0");
        jTextField_TCM.setText("0");
        jTextField_CGST.setText("0");
        jTextField_SGST.setText("0");
        jTextField_ST.setText("Rs. 0.0");
        jTextField_TAX.setText("Rs. 0.0");
        jTextField_TA.setText("Rs. 0.0");
        
        jCheckBox_Fruits.setSelected(false);
        jCheckBox_Veges.setSelected(false);
        jCheckBox_Pizza.setSelected(false);
        jCheckBox_Wafers.setSelected(false);
        jCheckBox_Biscuits.setSelected(false);
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jCheckBox_FruitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_FruitsActionPerformed
        if(jCheckBox_Fruits.isSelected()){
        jTextField_Fruits.setEditable(true);
        jTextField_Fruits.setText("");
        jTextField_Fruits.requestFocus();
        }
        else{
        jTextField_Fruits.setEditable(false);
        jTextField_Fruits.setText("0");
        }
        
        
        
        
    }//GEN-LAST:event_jCheckBox_FruitsActionPerformed

    private void jCheckBox_VegesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_VegesActionPerformed
        if(jCheckBox_Veges.isSelected()){
        jTextField_Veges.setEditable(true);
        jTextField_Veges.setText("");
        jTextField_Veges.requestFocus();
        }
        else{
        jTextField_Veges.setEditable(false);
        jTextField_Veges.setText("0");
        }
    }//GEN-LAST:event_jCheckBox_VegesActionPerformed

    private void jCheckBox_WafersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_WafersActionPerformed
        if(jCheckBox_Wafers.isSelected()){
        jTextField_Wafers.setEditable(true);
        jTextField_Wafers.setText("");
        jTextField_Wafers.requestFocus();
        }
        else{
        jTextField_Wafers.setEditable(false);
        jTextField_Wafers.setText("0");
        }
    }//GEN-LAST:event_jCheckBox_WafersActionPerformed

    private void jCheckBox_BiscuitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_BiscuitsActionPerformed
       if(jCheckBox_Biscuits.isSelected()){
        jTextField_Biscuits.setEditable(true);
        jTextField_Biscuits.setText("");
        jTextField_Biscuits.requestFocus();
        }
        else{
        jTextField_Biscuits.setEditable(false);
        jTextField_Biscuits.setText("0");
        }
    }//GEN-LAST:event_jCheckBox_BiscuitsActionPerformed

    private void jButton_clcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clcActionPerformed
        if(jCheckBox_Fruits.isSelected()|| jCheckBox_Veges.isSelected() || jCheckBox_Pizza.isSelected() ||
           jCheckBox_Wafers.isSelected() || jCheckBox_Biscuits.isSelected())
        {
        double f=Double.parseDouble(jTextField_Fruits.getText())*50;
        double v=Double.parseDouble(jTextField_Veges.getText())*50;
        double p=Double.parseDouble(jTextField_Pizza.getText())*50;
        double w=Double.parseDouble(jTextField_Wafers.getText())*50;
        double b=Double.parseDouble(jTextField_Biscuits.getText())*50;
        
        double totalitems= f+v+p+w+b;
        double del=totalitems*5/100;
        double mil= del*50/100;
        double subtotal=totalitems+del+mil;
        double cgst=subtotal*9/100;
        double sgst=cgst;
        double tax=cgst+sgst;
        double amount=subtotal+tax;
        
        String item=String.format("%.2f", totalitems);
        jTextField_TCI.setText((String)item);
        
        String d=String.format("%.2f", del);
        jTextField_TDC.setText((String)d);
        
        String m=String.format("%.2f", mil);
        jTextField_TCM.setText((String)m);
        
        String c=String.format("%.2f", cgst);
        jTextField_CGST.setText((String)c);
        
        String s=String.format("%.2f", sgst);
        jTextField_SGST.setText((String)s);
        
        String sub=String.format("%.2f", subtotal);
        jTextField_ST.setText((String)sub);
        
        String ta=String.format("%.2f", tax);
        jTextField_TAX.setText((String)ta);
        
        String tamount=String.format("%.2f", amount);
        jTextField_TA.setText((String)tamount);
        
        
            
        }
        else
        {
        txtDisplay.setText("Enter a choise");
        }
    }//GEN-LAST:event_jButton_clcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_CE;
    private javax.swing.JButton jButton_ans;
    private javax.swing.JButton jButton_clc;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_div;
    private javax.swing.JButton jButton_dot;
    private javax.swing.JButton jButton_mod;
    private javax.swing.JButton jButton_percent;
    private javax.swing.JButton jButton_plus;
    private javax.swing.JButton jButton_sub;
    private javax.swing.JCheckBox jCheckBox_Biscuits;
    private javax.swing.JCheckBox jCheckBox_Fruits;
    private javax.swing.JCheckBox jCheckBox_Pizza;
    private javax.swing.JCheckBox jCheckBox_Veges;
    private javax.swing.JCheckBox jCheckBox_Wafers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_SGST;
    private javax.swing.JLabel jLabel_ST;
    private javax.swing.JLabel jLabel_TCI;
    private javax.swing.JLabel jLabel_ta;
    private javax.swing.JLabel jLabel_tax;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField_Biscuits;
    private javax.swing.JTextField jTextField_CGST;
    private javax.swing.JTextField jTextField_Fruits;
    private javax.swing.JTextField jTextField_Pizza;
    private javax.swing.JTextField jTextField_SGST;
    private javax.swing.JTextField jTextField_ST;
    private javax.swing.JTextField jTextField_TA;
    private javax.swing.JTextField jTextField_TAX;
    private javax.swing.JTextField jTextField_TCI;
    private javax.swing.JTextField jTextField_TCM;
    private javax.swing.JTextField jTextField_TDC;
    private javax.swing.JTextField jTextField_Veges;
    private javax.swing.JTextField jTextField_Wafers;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
